const AIRPORT = [
  { name: 'Sân bay Quốc tế Nội Bài', code: 'HAN', shortName: 'SB-Nội Bài' },
  { name: 'Sân bay quốc tế Cát Bi ', code: 'HPH', shortName: 'SB-Cát Bi' },
  { name: 'Sân bay Điện Biên Phủ', code: 'DIN', shortName: 'SB- Điện Biên Phủ' },
  { name: 'Sân bay Thọ Xuân', code: 'THD', shortName: 'SB-Thọ Xuân' },
  { name: 'Sân bay quốc tế Vinh', code: 'VII', shortName: 'SB-Vinh' },
  { name: 'Sân bay Đồng Hới', code: 'VDH', shortName: 'SB-Đồng Hới' },
  { name: 'Sân bay quốc tế Phú Bài', code: 'HUI', shortName: 'SB-Phú Bài' },
  { name: 'Sân bay quốc tế Đà Nẵng', code: 'DAD', shortName: 'SB-Đà Nẵng' },
  { name: 'Sân bay quốc tế Chu Lai', code: 'VCL', shortName: 'SB-Chu Lai' },
  { name: 'Sân bay Phù Cát', code: 'UIH', shortName: 'SB- Phù Cát' },
  { name: 'Sân bay Tuy Hòa', code: 'TBB', shortName: 'SB-Tuy Hòa' },
  { name: 'Sân bay quốc tế Cam Ranh', code: 'CXR', shortName: 'SB-Cam Ranh' },
  { name: 'Sân bay Buôn Ma Thuột', code: 'BMV', shortName: 'SB-Buôn Ma Thuật' },
  { name: 'Sân bay Liên Khương', code: 'DLI', shortName: 'SB-Liên Khương' },
  { name: 'Sân bay Pleiku', code: 'PXU', shortName: 'SB-Pleiku' },
  { name: 'Sân bay quốc tế Tân Sơn Nhất', code: 'SGN', shortName: 'SB-Tân Sơn Nhất' },
  { name: 'Sân bay Cà Mau', code: 'CAH', shortName: 'SB-Cà Mau' },
  { name: 'Sân bay Côn Đảo', code: 'VCS', shortName: 'SB-Côn Đảo' },
  { name: 'Sân bay quốc tế Cần Thơ', code: 'VCA', shortName: 'SB-Cần Thơ' },
  { name: 'Sân bay Rạch Giá', code: 'VKG', shortName: 'SB-Rạch Gía' },
  { name: 'Sân bay quốc tế Phú Quốc', code: 'PQC', shortName: 'SB-Phú Quốc' },
  { name: 'Sân bay Quốc tế Vân Đồn', code: 'VDO', shortName: 'SB-Vân Đồn' },
];

export default AIRPORT;
